#! /usr/bin/env node

const { Client } = require('pg')
require("dotenv").config();

const CREATE_MONSTERS = `
CREATE TABLE IF NOT EXISTS monsters (
  monster_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR ( 50 ) NOT NULL,
  type_id INTEGER NOT NULL
);

INSERT INTO monsters (name, type_id)
VALUES
  ('goblin', 10),
  ('wolf', 2),
  ('ghost', 14);
`;

const CREATE_ABILITY_SCORES = `
CREATE TABLE IF NOT EXISTS ability_scores (
  ability_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  monster_id INT REFERENCES monsters(monster_id),
  ability_type VARCHAR (20) NOT NULL,
  score INT CHECK (score between 1 and 30) NOT NULL
);

INSERT INTO ability_scores (monster_id, ability_type, score)
VALUES
  (1, 'strength',8),
  (1, 'dexterity',14),
  (1,'constitution',10),
  (1,'intelligence',10),
  (1,'wisdom',8),
  (1,'charisma',8);
`;

const CREATE_TYPES = `
CREATE TABLE IF NOT EXISTS types (
  type_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  type_name VARCHAR ( 50 ),
  type_description VARCHAR ( 500)
);

INSERT INTO types (type_name, type_description)
VALUES
('aberration','Goals usually make no sense to humans. Behaviour should be weird.'),
('beast','Possess animal like intelligence and/or instict. Prioritizes food and the establishment and defense of territory.'),
('celestial','Concerned with cosmic order and purifying. Goal is to purge evil influences.'),
('construct','Only follow the instructions that they were programmed with. When instructions become impossible, they can go haywire.'),
('dragon', 'Want food and territory, but crave treasure and domination as well. Possess desire to demonstrate superiority. '),
('elemental', 'Forces of nature that are difficult to redirect once they have chosen a path. Defined by the temperaments associated with their elements.'),
('fey','Goals have a clear emotional or aesthetic aspect that might not make logical sense. Always personal regardless of the scale of their goals.'),
('fiend','Concerned with cosmic order and corruption. Goal is to introduce evil influences.'),
('giant','Goals usually revolve around rivalries with other giants. Interests are tightly dictated by species and place in hierarchy. Status is gained by claiming territory, wealth, rulership... etc.'),
('humanoid','Social creatures driven by politics and religion. Interested in territory, wealth, and domination.'),
('monstrosity','Possess animal like intelligence and/or instict. Prioritizes food and the establishment and defense of territory.'),
('ooze','Only interested in food.'),
('plant','Goals are only survival, self-propogation, and protection of its environment.'),
('undead','Driven by compulsions generated by event that caused them to rise from the dead.');
`;

const CREATE_SCORE_DESCRIPTIONS = `
CREATE TABLE IF NOT EXISTS score_descriptions (
  score_desc_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  ability_type VARCHAR ( 20 ) NOT NULL,
  min_score INT NOT NULL,
  max_score INT NOT NULL,
  stat_type VARCHAR (20),
  tier VARCHAR (20),
  range_description VARCHAR ( 500) NOT NULL
);

INSERT INTO score_descriptions (ability_type, min_score,max_score,stat_type,tier,range_description)
VALUES
  ('strength', 1, 8,'offense', 'low','Struggles to land impactful melee attacks. Often overpowered by physically stronger foes.'),
  ('strength', 9, 13, 'offense', 'medium','Reliable in melee combat but lacks overwhelming power. Can hold their ground against average enemies'),
  ('strength', 14, 17,'offense', 'high','A force to be reckoned with in melee combat, dealing significant damage and overpowering most opponents'),
  ('strength', 18, 20,'offense', 'extraordinary','A devastating melee powerhouse capable of smashing through defenses and dominating physical confrontations'),
  ('dexterity', 1, 8,'hybrid', 'low','Clumsy and slow to react. Frequently misses ranged attacks and is vulnerable to area effects'),
  ('dexterity', 9, 13, 'hybrid', 'medium','Adequately nimble to dodge attacks and hit moderately difficult ranged targets.'),
  ('dexterity', 14, 17,'hybrid', 'high','Exceptional agility allows them to evade most attacks and land precise ranged strikes consistently'),
  ('dexterity', 18, 20,'hybrid', 'extraordinary','A combat acrobat, effortlessly dodging attacks, landing pinpoint shots, and maneuvering around enemies.'),
  ('constitution', 1, 8,'defense', 'low','Easily fatigued and vulnerable to damage. Struggles to endure prolonged battles'),
  ('constitution', 9, 13, 'defense', 'medium','Able to withstand moderate physical punishment but may falter against strong attacks'),
  ('constitution', 14, 17,'defense', 'high','Remarkably tough, shrugging off blows that would incapacitate lesser combatants'),
  ('constitution', 18, 20,'defense', 'extraordinary','A juggernaut on the battlefield, capable of withstanding massive damage and enduring grueling encounters'),
  ('intelligence', 1, 8,'offense', 'low','Slow to analyze tactical situations. Struggles to adapt strategies or use spells effectively'),
  ('intelligence', 9, 13, 'offense', 'medium','Capable of casting most spells and formulating basic strategies during combat'),
  ('intelligence', 14, 17,'offense', 'high','A brilliant strategist with a mastery of spell usage, able to exploit enemy weaknesses efficiently'),
  ('intelligence', 18, 20,'offense', 'extraordinary','A combat genius, devising flawless strategies and casting spells with unmatched precision and creativity'),
  ('wisdom', 1, 8,'offense', 'low','Prone to making poor decisions in the heat of battle. Often fails to notice hidden dangers or traps'),
  ('wisdom', 9, 13, 'offense', 'medium','Shows solid awareness and judgment, supporting the team with steady tactical insights'),
  ('wisdom', 14, 17,'offense', 'high','Incredibly perceptive and intuitive, capable of predicting enemy moves and making critical interventions'),
  ('wisdom', 18, 20,'offense', 'extraordinary','Almost prescient, consistently making flawless decisions and spotting even the most subtle threats'),
  ('charisma', 1, 8,'offense', 'low','Struggles to command attention or inspire allies. Ineffective in intimidating or deceiving foes'),
  ('charisma', 9, 13, 'offense', 'medium','Competent at rallying allies and influencing opponents with persuasion or intimidation'),
  ('charisma', 14, 17,'offense', 'high','A charismatic leader who inspires allies and demoralizes foes with ease during combat.'),
  ('charisma', 18, 20,'offense', 'extraordinary','An awe-inspiring presence, capable of turning the tide of battle through sheer force of personality');
`;

async function main() {
  console.log("seeding...")
  const client = new Client()
  await client.connect();
  await client.query(CREATE_TYPES)
  await client.query(CREATE_MONSTERS)
  await client.query(CREATE_ABILITY_SCORES)
  await client.query(CREATE_SCORE_DESCRIPTIONS)
  await client.end();
  console.log("done")
}

main()